### PR TITLE
Added ability to plot an observed spectra (provided in simple csv - e…

### PR DESCRIPTION
**Pull request by CB-quakemodel**
…xample input file added to file samples) against spectra provided by gmpes (will test more before requesting review)

Example:

ResponseSpectra

### CODE REVIEW

**Comment by ManuelaVillani** [comment]
minor comment: could you change the observed spectrum to black or grey (a color not used for the GMMs)? also I'd change the style of the logic tree to dashed and black...

**Review by ManuelaVillani — COMMENTED** [review]
maybe I'd prefer to ahve a separate function for comparing spectra with observations: just because normally you have 1 magnitude and 1 distance in this case, just to simplify...

**Comment by CB-quakemodel** [comment]
Here is a revised color/line scheme for the plots. I will add the separate spectra plotting functon in an additional PR.

ResponseSpectra

**Comment by ManuelaVillani** [comment]
to change as discussed...

**Pull request closed without merging**
