### PR TITLE
20181221 maps

### PR DESCRIPTION
**Pull request by mmpagani**
This PR adds the code used to create the global hazard map from a mosaic of results. Some of the files required are left out since they are too large to be hosted on github.

### CODE REVIEW

**Comment by rcgee** [comment]
I think this branch is a few commits behind master

**Comment by rcgee** [comment]
Are the following paths the intended ones?
openquake/ghm/test/data/file_search/ACME/out/hazard_curve-mean-SA(0.1)_18149.csv
openquake/ghm/test/data/file_search/ACME/out/hazard_curve-rlz-000-SA(1.0)_18217.csv

**Comment by mmpagani** [comment]
Good catch. Grazie Robin.

**Comment by mmpagani** [comment]
> Are the following paths the intended ones?
> openquake/ghm/test/data/file_search/ACME/out/hazard_curve-mean-SA(0.1)_18149.csv
> openquake/ghm/test/data/file_search/ACME/out/hazard_curve-rlz-000-SA(1.0)_18217.csv

Where do you see them?

**Comment by rcgee** [comment]
https://github.com/GEMScienceTools/oq-mbtk/blob/51e21c7ab884baf3be3f93d5604623078454d098/openquake/ghm/test/data/file_search/ACME/out/hazard_curve-rlz-000-SA(1.0)_18217.csv

https://github.com/GEMScienceTools/oq-mbtk/blob/51e21c7ab884baf3be3f93d5604623078454d098/openquake/ghm/test/data/file_search/ACME/out/hazard_curve-rlz-000-SA(1.0)_18217.csv

**Comment by rcgee** [comment]
LGTM

**Pull request merged**
